"""Add foreign key relationship between Quiz and QuizQuestion

Revision ID: 3e683625dfbd
Revises: e46645b92ebc
Create Date: 2025-02-28 19:36:27.332374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e683625dfbd'
down_revision = 'e46645b92ebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('correct_answer', sa.String(length=1), nullable=False))
        batch_op.drop_column('question_text')
        batch_op.drop_column('correct_option')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_option', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('question_text', sa.TEXT(), nullable=False))
        batch_op.drop_column('correct_answer')
        batch_op.drop_column('text')

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
