"""Added duration to Quiz and student_name to QuizResult

Revision ID: a6daa69a652f
Revises: 2dfe75854c30
Create Date: 2025-03-01 09:41:22.075670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6daa69a652f'
down_revision = '2dfe75854c30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=False))
        batch_op.drop_column('is_live')
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('is_live', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
